version: '{build}'

image:
  - Ubuntu
  - Visual Studio 2013

configuration:
  - RelWithDebInfo

environment:
  SAMP_SDK_ROOT: sdk

  matrix:
  - STATIC: ON
  - STATIC: OFF

for:
  -
    matrix:
      only:
        - image: Ubuntu

    install:
      - sudo apt-add-repository -y ppa:kubuntu-ppa/backports
      - sudo apt-get update -qq
      - sudo apt-get install -y linux-libc-dev:i386 gcc-4.8 gcc-4.8-multilib
                                g++-4.8 g++-4.8-multilib cmake cmake python-pip
                                python-ply doxygen
      - sudo rm /usr/local/bin/doxygen || true
      - git clone --depth 1 https://github.com/Zeex/samp-plugin-sdk.git sdk

    before_build:
      - mkdir build && cd build
      - cmake .. -DCMAKE_C_COMPILER=gcc-4.8
                 -DCMAKE_CXX_COMPILER=g++-4.8
                 -DSAMPGDK_STATIC=${STATIC}
                 -DSAMPGDK_BUILD_PLUGINS=ON
                 -DSAMPGDK_BUILD_AMALGAMATION=ON

    build_script:
      - make
      - make package

    artifacts:
      - path: build/sampgdk-*-linux.tar.gz
        name: Binary Package (shared library)
      - path: build/sampgdk-*-linux-static.tar.gz
        name: Binary Package (static library)
      - path: build/sampgdk-*-amalgamation.zip
        name: Amalgamation (concatenated source code)

  -
    matrix:
      only:
        - image: Visual Studio 2013

    install:
      - choco install -y doxygen.install
      - set PATH=%PATH%;C:\Python27\Scripts
      - pip install ply
      - git clone https://github.com/Zeex/samp-plugin-sdk.git sdk

    before_build:
      - mkdir build && cd build
      - cmake .. -G "Visual Studio 10 2010"
                 -DSAMPGDK_STATIC=%STATIC%
                 -DSAMPGDK_BUILD_PLUGINS=ON
                 -DSAMPGDK_BUILD_AMALGAMATION=ON

    build_script:
      - cmake --build . --config %CONFIGURATION%
      - cmake --build . --config %CONFIGURATION% --target package

    artifacts:
      - path: build/sampgdk-*-win32.zip
        name: Binary Package (DLL)
      - path: build/sampgdk-*-win32-static.zip
        name: Binary Package (static library)
      - path: build/sampgdk-*-amalgamation.zip
        name: Amalgamation (concatenated source code)
